version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn

  pre_build:
    commands:
      - yarn
      - chmod +x ./build/docs/source_version.sh
      - export PACKAGE_VERSION=$(./build/docs/source_version.sh)

  build:
    commands:
      - yarn build:reference
      - yarn build:guide

      # The documentation, which has built-in versioning
      - cp docs/guide/website/build/botpress-docs/index.html docs/guide/website/build/botpress-docs/docs/index.html
      - aws s3 sync docs/guide/website/build/botpress-docs s3://botpress-docs/

      # Reference for both current version from package.json but also branch name / latest
      - aws s3 sync docs/reference/public s3://botpress-reference/
      - aws s3 sync docs/reference/public s3://botpress-reference/$PACKAGE_VERSION
      - aws s3 sync .github s3://botpress-reference/.github
      - aws s3 sync .github s3://botpress-reference/$PACKAGE_VERSION/.github
