name: Codestyle
on: [pull_request]
jobs:
  run_prettier:
    name: Run Prettier on codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          yarn
      - name: Run Prettier
        run: |
          ./node_modules/prettier/bin-prettier.js --check '{src,modules}/**/*.ts' '!**/*.d.ts'
  tslint:
    name: Run TSLint on codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          yarn
      - name: Run TSLint
        run: |
          yarn run tslint
      - name: Get file changes
        id: get_file_changes
        uses: dorner/file-changes-action@v1.2.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          plaintext: true
      - name: Filter files
        id: filtered_files
        run: |
          echo ::set-output name=files::$(node build/tslint-filter-files.js ${{ steps.get_file_changes.outputs.files }})
      - name: Run TSLint (new rules)
        run: |
          yarn run tslint -c tslint.newrules.json ${{ steps.filtered_files.outputs.files }}
